export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAIL = "GET_MOVIE_DETAILS_FAIL";
export const GET_MOVIE_DETAILS_RESET = "GET_MOVIE_DETAILS_RESET";

export const TOP_RATED_MOVIE_LIST_REQUEST = "TOP_RATED_MOVIE_LIST_REQUEST";
export const TOP_RATED_MOVIE_LIST_SUCCESS = "TOP_RATED_MOVIE_LIST_SUCCESS";
export const TOP_RATED_MOVIE_LIST_FAIL = "TOP_RATED_MOVIE_LIST_FAIL";

export const GET_RANDOM_MOVIE_LIST_REQUEST = "GET_RANDOM_MOVIE_LIST_REQUEST";
export const GET_RANDOM_MOVIE_LIST_SUCCESS = "GET_RANDOM_MOVIE_LIST_SUCCESS";
export const GET_RANDOM_MOVIE_LIST_FAIL = "GET_RANDOM_MOVIE_LIST_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const DELETE_ALL_MOVIE_REQUEST = "DELETE_ALL_MOVIE_REQUEST";
export const DELETE_ALL_MOVIE_SUCCESS = "DELETE_ALL_MOVIE_SUCCESS";
export const DELETE_ALL_MOVIE_FAIL = "DELETE_ALL_MOVIE_FAIL";


export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";